[package]
name                   = "eez-dev-node"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true
description            = "Unanchored local-development eez sequencer node."
default-run            = "eez-dev-node"

[dependencies]
eez-driver.workspace    = true
eez-node-common.workspace = true

reth-node-builder.workspace  = true
reth-node-ethereum.workspace = true

eyre.workspace    = true
tracing.workspace = true

[lints]
workspace = true
