//! Compatibility vectors produced by the pinned Solidity protocol.
//!
//! The expected values are copied from and independently asserted by
//! `contracts/test/RollingHashVectors.t.sol`; they are not generated by the
//! Rust implementation under test.

use std::{fs, path::PathBuf};

use alloy_primitives::{B256, b256};
use eez_protocol::rolling_hash::{EntryRollingHash, StaticCallRollingHash};
use serde::Deserialize;

const EXPECTED_PROTOCOL_COMMIT: &str = "6fcc90b65063831cb7797e9fa361004064d28f9f";
const EXPECTED_SOLIDITY_ORACLE: &str = "contracts/test/RollingHashVectors.t.sol";

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Vectors {
    schema_version: u64,
    protocol_commit: String,
    solidity_oracle: String,
    l1_seed: String,
    l2_seed: String,
    after_call_begin: String,
    after_call_end: String,
    after_nested_begin: String,
    after_nested_end: String,
    after_call_not_found: String,
    after_static_success: String,
    after_static_failure: String,
}

fn load_vectors() -> Vectors {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/rolling_hash_vectors.json");
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    let vectors: Vectors = serde_json::from_str(&raw).expect("valid rolling-hash vector fixture");
    assert_eq!(vectors.schema_version, 1, "fixture schema version");
    assert_eq!(
        vectors.protocol_commit, EXPECTED_PROTOCOL_COMMIT,
        "fixture protocol commit"
    );
    assert_eq!(
        vectors.solidity_oracle, EXPECTED_SOLIDITY_ORACLE,
        "fixture Solidity oracle"
    );
    vectors
}

fn parse_hash(value: &str) -> B256 {
    value.parse().expect("valid bytes32 fixture value")
}

#[test]
fn entry_vectors_match_solidity() {
    let expected = load_vectors();
    let proxy_entry_hash =
        b256!("0000000000000000000000000000000000000000000000000000000000000033");
    let call_hash = b256!("0000000000000000000000000000000000000000000000000000000000000044");
    let updates = [
        (
            1,
            b256!("0000000000000000000000000000000000000000000000000000000000000011"),
        ),
        (
            u64::MAX,
            b256!("0000000000000000000000000000000000000000000000000000000000000022"),
        ),
    ];

    let mut l1 = EntryRollingHash::seed_for_l1(updates, proxy_entry_hash);
    assert_eq!(l1.current(), parse_hash(&expected.l1_seed), "L1 seed");

    let l2 = EntryRollingHash::seed_for_l2(proxy_entry_hash);
    assert_eq!(l2.current(), parse_hash(&expected.l2_seed), "L2 seed");

    l1.call_begin(call_hash);
    assert_eq!(
        l1.current(),
        parse_hash(&expected.after_call_begin),
        "CALL_BEGIN"
    );

    l1.call_end(true, &[0xaa, 0xbb, 0xcc]);
    assert_eq!(
        l1.current(),
        parse_hash(&expected.after_call_end),
        "CALL_END"
    );

    l1.nested_begin(call_hash);
    assert_eq!(
        l1.current(),
        parse_hash(&expected.after_nested_begin),
        "NESTED_BEGIN"
    );

    l1.nested_end();
    assert_eq!(
        l1.current(),
        parse_hash(&expected.after_nested_end),
        "NESTED_END"
    );

    l1.call_not_found(call_hash);
    assert_eq!(
        l1.current(),
        parse_hash(&expected.after_call_not_found),
        "CALL_NOT_FOUND"
    );
}

#[test]
fn static_vectors_match_solidity() {
    let expected = load_vectors();
    let mut rolling_hash = StaticCallRollingHash::new();

    rolling_hash.append(true, &[0xaa, 0xbb, 0xcc]);
    assert_eq!(
        rolling_hash.current(),
        parse_hash(&expected.after_static_success),
        "first static result"
    );

    rolling_hash.append(false, &[0xde, 0xad, 0xbe, 0xef]);
    assert_eq!(
        rolling_hash.current(),
        parse_hash(&expected.after_static_failure),
        "second static result"
    );
}
